name: SQMS
description: Smart Queue Management System
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0F0F13"
  image: "icon.png"
  android_12:
    image: "icon.png"
    color: "#0F0F13"

flutter:
  uses-material-design: true
